### PR TITLE
Alternate approach to reordering field names

### PR DESCRIPTION
**Pull request by brianhigh**
Started using the approach suggested in #81 for reordering field names in exportRecords_offline.R. This is working with my data set. However, this requires that the header row is included in the CSV. Then refactored to be as close to the original nutterb repo as possible. At this point, the only main differences are the the CSVs need to have their headers and that the extra fields in the record form data do not have to be guessed  based on conventions. The benefits are that this function finally works with our data and with more reasonable changes to the code compared to my earlier pull request. I'll send my sample dataset by email to nutterb for testing. I do not have access to the project's web UI in REDCap, just to the API. We need to be able to bring in REDCap data from CSV and from the equivalent datasets in a SQL database. That's why it is important to us that we have an "offline" function like this.

### CODE REVIEW

**Comment by nutterb** [comment]
Thank you so much.  I like that the problematic fields are handled, and you made it much cleaner than my original attempts.  I'll need to employ some of your strategies elsewhere in the package.

**Comment by brianhigh** [comment]
My only concern with this approach is if the field names get mangled as they are turned into column names in R upon import from the record form data. This approach assumes this will not happen, which may not be a reasonable assumption. Some of my earlier code was meant to address this issue in a safer way, but it was getting too complicated and ugly, so I removed it. Our project has nice field names, but others may not. I don't know if REDCap has field name restrictions that would be aligned with R's column name standards or not.

**Comment by wibeasley** [comment]
>I don't know if REDCap has field name restrictions that would be aligned with R's column name standards or not.

@brianhigh, as of 6.14.2, REDCap's allowed variable names are a strict subset of R's.  Just underscores, digits, and lowercase letters.  (And it's even smaller than that, because I don't think REDCap variables can start with underscores or digits.)

I haven't followed everything in these recent threads, but it seems like your assumptions (ie, "This approach assumes this will not happen") are a nice way to eliminate worrying about these conversions.

REDCap 6.14.2:
image

**Comment by nutterb** [comment]
I wI'll confirm @wibeasley 's comment. REDCap is designed to use field names that are compatible with R, SAS, SPSS, STATA, and I believe they considered some other stats software. The intersection of allowable field names between those programs is quite small. 

The only case I know of in which REDCap itself mangled the field names was fixed back in version 5.8.20 (?), and `redcapAPI` has a mechanism to correct that.

**Comment by brianhigh** [comment]
Ah, okay, perfect. My concerns are allayed. Thanks! :)

**Pull request merged**
