### PR TITLE
Added missing @export, support for survey arg

### PR DESCRIPTION
**Pull request by brianhigh**
Added @export fieldToVar, as it was missing from fieldToVar.R. Added support for survey argument to allow retention of survey fields in output of exportRecords_offline function.

### CODE REVIEW

**Comment by nutterb** [comment]
Do you have a particular need for `fieldToVar` to be exported?  I have never intended to export it; it has no argument validations and is very susceptible to failure outside of a controlled environment. That being said, if you have a specific use case in mind, I'm not opposed to exporting it. 

Thanks for working on this.

**Comment by brianhigh** [comment]
I found that I was getting errors when debugging this error in exportRecords_offline.R:

# FAILS with the error:
#   Error in `[.data.frame`(`*tmp*`, , field_names) : 
#   undefined columns selected
#   In addition: There were 50 or more warnings (use warnings() to see 
#   the first 50)

**Comment by brianhigh** [comment]
Okay, I reverted the export of fieldToVar and exportRecords_offline still works for me. Sorry for the trouble.

**Comment by brianhigh** [comment]
Support for the survey=TRUE argument in exportRecords_offline would still be nice, though.

**Comment by nutterb** [comment]
I'm actually somewhat relieved. I'm guessing you had something defined in your local environment that was masking an object. If not, there would have to be a latent bug in the package code.

I'll work on merging this in. 

Thanks again!

**Comment by brianhigh** [comment]
Thanks, much appreciated!

**Comment by nutterb** [comment]
I hope you'll forgive my overambition--after studying your changes, it seemed there may be a way to preserve the survey fields without adding an argument.  I updated the main branch with code where if the survey fields are in the file, they are preserved.  If `dates = TRUE`, they are converted to `POSIXct` objects.  It's a little bit messier than your fix, but means the user doesn't have to explicitly request the survey fields.

More importantly, the order of the variables in the original download is preserved.  I'm not sure that was the case before.

Please give this new version a go and let me know if it captures your intent. (`devtools::install_github("nutterb/redcapAPI")`)  

Thanks for bringing this to my attention.  I had never realized I had excluded the survey information here before.

**Comment by brianhigh** [comment]
Hmmm. Tried it. Getting errors:

Error in `[.data.frame`(x, , field_names, drop = FALSE) : 
  undefined columns selected

This is from:

# Prepare dataframe to write to CSV.
rcform <- exportRecords(rcon, factors=FALSE, survey = TRUE)
rcmeta <- exportMetaData(rcon)

# Create the data folder if needed.
datadir <- 'csvdata'
dir.create(file.path(datadir), showWarnings = FALSE, recursive = TRUE)

# Save REDCap data to CSV files.
writeCSV <- function(df, filepath, col.names=TRUE) {
    write.table(df, filepath, row.names = FALSE, col.names=col.names, 
                sep=',', na = '', qmethod='double', 
                fileEncoding = 'ASCII', eol = '\r\n')
}
writeCSV(rcform, file.path(datadir, 'rcform.csv'))
writeCSV(rcmeta, file.path(datadir, 'rcmeta.csv'), col.names=FALSE)

# Read from CSV files and create dataframe with column labels (default).
df <- exportRecords_offline(file.path(datadir, 'rcform.csv'), file.path(datadir, 'rcmeta.csv'))

**Comment by nutterb** [comment]
I get the same error until I change 

```r
writeCSV(rcmeta, file.path(datadir, 'rcmeta.csv'), col.names=FALSE)
```

to 

```r
writeCSV(rcmeta, file.path(datadir, 'rcmeta.csv'), col.names=TRUE)
```

Since `exportRecords_offline` was intended to work with the downloaded CSVs (I originally wrote it when I couldn't wait for my REDCap Administrator to authorize a token), it assumes that there is a row of column headers.  It doesn't really matter what they headers are, they get overwritten to the column names that come from the API within the function.

when you set `col.names = FALSE`, your subject ID field became the column header, and couldn't be found to match with `field_names`.

**Comment by brianhigh** [comment]
When I try as you have suggested, I get a new error:

```
Error in `[[<-.data.frame`(`*tmp*`, i, value = integer(0)) : 
  replacement has 0 rows, data has 5
```

I don't know what this is about.

**Comment by brianhigh** [comment]
I think the problem may lie in that the field_names from the metadata is not a complete list of field names in the form record data.

This is the part of the function where the form record data is read in up until just before the function returns the result.

In my version those last few lines are skipped of you pass survey=TRUE, and those are the ones fiddling with the column names. It is too late at night for me to dig into this, but I think the answer is somewhere in there. :)

```
    x <- utils::read.csv(datafile, stringsAsFactors=FALSE, na.strings="")#[, field_names, drop=FALSE]

    lapply(field_names,
           function(i)
           {
             x[[i]] <<- fieldToVar(as.list(meta_data[meta_data$field_name==sub("___[a-z,A-Z,0-9,_]+", "", i),]),
                                   x[[i]],factors,dates, checkboxLabels, vname=i)
           }
    )

    if (labels) Hmisc::label(x[, field_names], self=FALSE) <- field_labels

   if ("redcap_data_access_group" %in% names(x)) field_names <- c(field_names[1], "redcap_data_access_group", field_names[-1])
   if ("redcap_event_name" %in% names(x)) field_names <- c(field_names[1], "redcap_event_name", field_names[-1])
   field_names <- c(field_names, paste0(unique(meta_data$form_name), "_complete"))
   x <- x[, field_names, drop=FALSE]
```

**Comment by nutterb** [comment]
That's peculiar.  Let's try this next:

1. `devtools::install_github("nutterb/redcapAPI", ref = "bug-hunt")
2. Run the code again.  I've added a bunch of `print("BreakN")` lines.  If you can tell me when value of `N` is the largest, that will help narrow down the exact point in the code (there are 3 it could be, and I suspect heavily it's the last)
3. Rather than using the CSV files we've converted from the API, download the Raw CSV file from the REDCap UI and the metadata from the REDCap UI.  Do you get the same results with those files? (this will tell us if the problem is oddities we've created from converting the API data)
4. What version of REDCap are you using?  I'm using 6.5.0.  There may be a difference between versions that has to be handled.

**Comment by brianhigh** [comment]
There was no handling of redcap_survey_identifier and _timestamp fields. That's why the field_names vector was shorter than the names(x) vector for a dataset with survey=TRUE.

But even if you do something like this, the order of the field_names will still not match the correct field order in x, because the _complete and _timestamp fields will be placed at the end of the field_names vector. 

```
if ("redcap_data_access_group" %in% names(x)) field_names <- c(field_names[1], "redcap_data_access_group", field_names[-1])
if ("redcap_event_name" %in% names(x)) field_names <- c(field_names[1], "redcap_event_name", field_names[-1])
field_names <- c(field_names, paste0(unique(meta_data$form_name), "_complete"))
if ("redcap_survey_identifier" %in% names(x)) field_names <- c(field_names[1], "redcap_survey_identifier", field_names[-1])
timestamps <- paste0(unique(meta_data$form_name), "_timestamp")
if (timestamps %in% names(x)) field_names <- c(field_names, timestamps)
x <- x[, field_names, drop=FALSE]
```

While you might be able to guess the order when working with a single form, a dataset that contains multiple forms will require that you place them more carefully.

For example, in my test datatset, the positions of those field names are:

```
> grep("_timestamp$", names(rcform))
[1]  3  8 24 66 88
> grep("_complete$", names(rcform))
[1]   7  23  65  87 191
```

But if I run that code snippet on the field_names vector, the positions are at the end of the vector:

```
> grep("_timestamp$", field_names)
[1] 187 188 189 190 191
> grep("_complete$", field_names)
[1] 182 183 184 185 186
```

How do we insert those names in their proper positions? Perhaps a "merge" of some sort?

**Comment by brianhigh** [comment]
This approach (below) seems to work, but you need to have access to the original field names from the form record dataset. If the script in redcapAPI was modified to accept CSVs with headers, this could work.

```
# Given two datasets, rcform and rcmeta, and the CSVs exported from REDCap, with headers,
# replace missing field names from rcform into vector of field names from rcmeta$field_name.

# Read field names into a vector.
field_names <- rcmeta$field_name

# Save dataframes using names consistent with redcapAPI script.
x <- rcform
meta_data <- rcmeta

# Find the variable names in the record form dataset from the original CSV file.
x_field_names <- as.vector(t(read.csv(file.path(datadir, 'rcform.csv'), header=F, stringsAsFactors = FALSE, colClasses = 'character', nrows = 1)))

# Find the extra variable names in x that are not in the field_names vector in metadata.
x_field_names_extra <- x_field_names[! x_field_names %in% field_names]

# Create a dataframe of these extra variable names, storing their original index.
x_field_names_df <- data.frame(index=1:ncol(x), field_name=x_field_names, stringsAsFactors = FALSE)
x_field_names_extra_df <- x_field_names_df[x_field_names_df$field_name %in% x_field_names_extra, ]

# Replace index with the index of previous item for use with append()'s 'after' argument.
x_field_names_extra_df$index <- x_field_names_extra_df$index - 1

# Insert the extra field names into the field_names vector in the correct position.
if (nrow(x_field_names_extra_df) != 0) {
    for (i in 1:nrow(x_field_names_extra_df)) {
        field_names <- append(field_names, x_field_names_extra_df[i, 'field_name'], after=x_field_names_extra_df[i, 'index'])
    }
}

# Check that the two vectors are identical.
identical(field_names, x_field_names)
# TRUE
```

**Comment by brianhigh** [comment]
Provided a working example of this approach in new pull request #83.

**Comment by brianhigh** [comment]
Oh, I just saw your post from early this morning. Sorry I did not see until now. I will try those steps you listed. I'll get back to your tomorrow with results and our sample dataset.

**Pull request closed without merging**
